server:
  port: 8888
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/rafaelribeirowt/raeltec-config-server.git
          default-label: main
          search-paths:
          - 'greeting-service*'