name: Continuous Integration with Github

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Setup Java JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
         
      - name: Build Eureka Naming Container Image
        working-directory: ./ms-naming-server/
        run: mvn spring-boot:build-image -DskipTests
        
      - name: Build Api Gateway Container Image
        working-directory: ./ms-api-gateway/
        run: mvn spring-boot:build-image -DskipTests
        
      - name: Build Cambio Microservice Jar
        working-directory: ./ms-cambio-service/
        run: mvn clean package -DskipTests
        
      - name: Build Book Microservice Jar
        working-directory: ./ms-book-service/
        run: mvn clean package -DskipTests
      
      - name: Docker Compose Build
        working-directory: ./
        run: docker-compose build  
        
      
          
      - name: Tag dockerHub container ms-naming-server    
        run: docker tag ${{ secrets.DOCKER_USERNAME }}/ms-naming-server:0.0.1-SNAPSHOT ${{ secrets.DOCKER_USERNAME }}/ms-naming-server:${{github.run_id}}
      
      - name: Tag dockerHub container ms-naming-server latest   
        run: docker tag ${{ secrets.DOCKER_USERNAME }}/ms-naming-server:0.0.1-SNAPSHOT ${{ secrets.DOCKER_USERNAME }}/ms-naming-server:latest
         
      - name: Tag dockerHub container ms-api-gateway 
        run: docker tag ${{ secrets.DOCKER_USERNAME }}/ms-api-gateway:0.0.1-SNAPSHOT ${{ secrets.DOCKER_USERNAME }}/ms-api-gateway:${{github.run_id}}
       
      - name: Tag dockerHub container ms-api-gateway latest
        run: docker tag ${{ secrets.DOCKER_USERNAME }}/ms-api-gateway:0.0.1-SNAPSHOT ${{ secrets.DOCKER_USERNAME }}/ms-api-gateway:latest
         
      - name: Tag dockerHub container ms-cambio-service 
        run: docker tag ${{ secrets.DOCKER_USERNAME }}/ms-cambio-service:0.0.1-SNAPSHOT ${{ secrets.DOCKER_USERNAME }}/ms-cambio-service:${{github.run_id}}
               
      - name: Tag dockerHub container ms-cambio-service latest
        run: docker tag ${{ secrets.DOCKER_USERNAME }}/ms-cambio-service:0.0.1-SNAPSHOT ${{ secrets.DOCKER_USERNAME }}/ms-cambio-service:latest   
        
      - name: Tag dockerHub container ms-book-service 
        run: docker tag ${{ secrets.DOCKER_USERNAME }}/ms-book-service:0.0.1-SNAPSHOT ${{ secrets.DOCKER_USERNAME }}/ms-book-service:${{github.run_id}}
         
      - name: Tag dockerHub container ms-book-service latest
        run: docker tag ${{ secrets.DOCKER_USERNAME }}/ms-book-service:0.0.1-SNAPSHOT ${{ secrets.DOCKER_USERNAME }}/ms-book-service:latest
      
      - name: Push dockerHub container ms-naming-server 
        run: docker push ${{ secrets.DOCKER_USERNAME }}/ms-naming-server:${{github.run_id}}
       
      - name: Push dockerHub container ms-naming-server latest
        run: docker push ${{ secrets.DOCKER_USERNAME }}/ms-naming-server:latest
              
      - name: Push dockerHub container ms-api-gateway
        run: docker push ${{ secrets.DOCKER_USERNAME }}/ms-api-gateway:${{github.run_id}}
        
      - name: Push dockerHub container ms-api-gateway latest
        run: docker push ${{ secrets.DOCKER_USERNAME }}/ms-api-gateway:latest
        
      - name: Push dockerHub container ms-cambio-service 
        run: docker push ${{ secrets.DOCKER_USERNAME }}/ms-cambio-service:${{github.run_id}}
        
      - name: Push dockerHub container ms-cambio-service latest
        run: docker push ${{ secrets.DOCKER_USERNAME }}/ms-cambio-service:latest        
          
      - name: Push dockerHub container ms-book-service 
        run: docker push ${{ secrets.DOCKER_USERNAME }}/ms-book-service:${{github.run_id}} 

      - name: Push dockerHub container ms-book-service latest
        run: docker push ${{ secrets.DOCKER_USERNAME }}/ms-book-service:latest
