name: Continuous Integration with Github

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Setup Java JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
         
      - name: Build Eureka Naming Container Image
        working-directory: ./ms-naming-server/
        run: mvn spring-boot:build-image -DskipTests
        
      - name: Build Api Gateway Container Image
        working-directory: ./ms-api-gateway/
        run: mvn spring-boot:build-image -DskipTests
        
      - name: Build Cambio Microservice Jar
        working-directory: ./ms-cambio-service/
        run: mvn clean package -DskipTests
        
      - name: Build Book Microservice Jar
        working-directory: ./ms-book-service/
        run: mvn clean package -DskipTests
      
      - name: Docker Compose Build
        working-directory: ./
        run: docker-compose build  
        
      
          
      - name: Push dockerHub container registry    
        run:  
          docker push rafaelribeirowt/ms-naming-server:0.0.1-SNAPSHOT    
          docker push rafaelribeirowt/ms-api-gateway:0.0.1-SNAPSHOT        
          docker push rafaelribeirowt/ms-cambio-service:0.0.1-SNAPSHOT   
          docker push rafaelribeirowt/ms-book-service:0.0.1-SNAPSHOT
          